on:
 push:
   - branches:
       master

jobs:
  docker-image:
    runs-on: ubuntu-latest
    container: docker:stable
    env:
      CI_REGISTRY_IMAGE: bitcast/icecast-record
    
    services:
      docker:
        image: docker:stable-dind
        env:
          DOCKER_DRIVER: overlay2

    steps:
      - name: Check out repositrory code
        uses: actions/checkout@v2
      
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: {{ env.CI_REGISTRY_IMAGE }}
          tags: v1, latest
          registry: dockerhub.io
          dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}