on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 1 * *'

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repositrory code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: ${{ secrets.CI_REGISTRY_IMAGE }}
          tags: latest, ${{ github.sha }}
          registry: docker.io
          dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}